name: ci

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.2
#    - uses: actions/cache@v2
#      with:
#        path: ~/.cache/pip
#        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
    - name: Test
      run: |
        (cd deployments && ln -snf dev .active)
        source environment
        make virtualenv
        source .venv/bin/activate
        # make requirements
        # Hack: The use of chrgp compensates for a quirk of Docker. The PyCharm image
        # used by make format sets up a user called `developer` and assigns it UID
        # 1000. Travis is running as UID 2000. An alternative would be to pass --user
        # to `docker run` and bind-mount an /etc/passwd that maps that to `developer`.
        # We also need write permissions for the group
        chmod -R g+w . && sudo chgrp -R 1000 . && make format && sudo chgrp -R $(id -g) .
        docker info
        sudo ls /var/lib/docker/image/overlay2
        sudo cat /var/lib/docker/image/overlay2/repositories.json | jq .
        sudo ls /var/lib/docker/image/overlay2/imagedb/content/sha256
